nvblox:
  projective_integrator_max_integration_distance_m: 2.5

  use_2d_esdf_mode: true
  experimental_use_ground_plane_estimation: true
  ground_points_candidates_min_z_m: -2.0
  slice_height_above_plane_m: 0.3
  slice_height_thickness_m: 0.5

  workspace_bounds_type: 1 # 1 = WORKSPACE_BOUNDS_TYPE_HEIGHT_BOUNDS
  workspace_bounds_min_height_m: -2.0
  workspace_bounds_max_height_m: 2.0

  mapping_type_dynamic: true
  mapping_type_static_occupancy: false

  fit_to_z0: false

cuvslam:
  cfg_enable_slam: true # Enable localization and mapping
  ros_frame_conversion: true # Convert input/output poses from/to ROS frame
  print_format: tum # Format of output poses (options: matrix, tum)

  cfg_denoising: false # Enable image denoising (matches navigation: enable_image_denoising: False)
  cfg_max_frame_delta_s: 0.034 # Set maximum camera frame time in seconds (matches navigation: image_jitter_threshold_ms: 34.0)
  cfg_horizontal: false # Enable tracking for rectified cameras with principal points on horizontal line (Oak uses unrectified)

  # Image masking
  border_bottom: 0 # Bottom border to ignore in pixels (navigation: img_mask_bottom: 30)
  border_left: 0 # Left border to ignore in pixels (navigation: img_mask_left: 150)
  border_right: 0 # Right border to ignore in pixels (navigation: img_mask_right: 30)
  border_top: 0 # Top border to ignore in pixels (0 to use full frame)

  cfg_multicam_mode: 2 # Multicamera mode: moderate (0), performance (1) or precision (2)
  cfg_odom_mode: 0 # Odometry mode: Multicamera (0), Inertial (1), RGBD (2)
  cfg_planar: false # Slam poses are so that camera moves on horizontal plane (default: false)
  cfg_slam_max_map_size: 300 # Maximum numbers of poses in SLAM pose graph, 0 means unlimited
  cfg_sync_slam: true # Run localization and mapping in same thread with visual odometry

  # repeat
  repeat: 1 # Number of repetitions of the dataset

  # export
  debug_dump: false # Enable debug dump (saves to <map_dir>/logs when true)
