stereo_cameras:
  - name: front_stereo_camera
    left: /front_stereo_camera/left/image_rect
    left_camera_info: /front_stereo_camera/left/camera_info_rect
    right: /front_stereo_camera/right/image_rect
    right_camera_info: /front_stereo_camera/right/camera_info_rect
  - name: back_stereo_camera
    left: /back_stereo_camera/left/image_rect
    left_camera_info: /back_stereo_camera/left/camera_info_rect
    right: /back_stereo_camera/right/image_rect
    right_camera_info: /back_stereo_camera/right/camera_info_rect
  - name: left_stereo_camera
    left: /left_stereo_camera/left/image_rect
    left_camera_info: /left_stereo_camera/left/camera_info_rect
    right: /left_stereo_camera/right/image_rect
    right_camera_info: /left_stereo_camera/right/camera_info_rect
  - name: right_stereo_camera
    left: /right_stereo_camera/left/image_rect
    left_camera_info: /right_stereo_camera/left/camera_info_rect
    right: /right_stereo_camera/right/image_rect
    right_camera_info: /right_stereo_camera/right/camera_info_rect
